const SUBMITTING_CONTACT           = 'SUBMITTING_CONTACT';

const  GETTING_PHONE_NUMBER_INPUT        = 'GETTING_PHONE_NUMBER_INPUT';
const  GETTING_CONTACT_NAME_INPUT        = 'GETTING_CONTACT_NAME_INPUT';
const  GETTING_DAYS_HELD_INPUT           = 'GETTING_DAYS_HELD_INPUT';


module.exports = {
    SUBMITTING_CONTACT,
    GETTING_PHONE_NUMBER_INPUT,
    GETTING_CONTACT_NAME_INPUT,
    GETTING_DAYS_HELD_INPUT,
};
